//! Music and sound effects. Every note is generated by Emberdeep's built-in
//! synthesizer at runtime; there are no audio assets.
//!
//! - `synth`: oscillators, voices (ADSR, filters, vibrato), echo, limiter.
//! - `seq`: the tracker notation and the real-time song player.
//! - `songs`: the soundtrack; `sfx`: the sound effects; `patches`: instruments.
//! - `engine`: mixes songs (with crossfades) and effects.
//! - `backend` (feature `audio`): plays the engine through rodio on a
//!   background thread. Without the feature, or without an output device,
//!   `Audio` is silent and every call is a cheap no-op.

#[cfg(feature = "audio")]
mod backend;
pub(crate) mod engine;
pub(crate) mod patches;
pub(crate) mod seq;
pub(crate) mod sfx;
pub(crate) mod songs;
pub(crate) mod synth;

use std::time::Instant;

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Track {
    Title,
    Town,
    TownSorrow,
    Undercroft,
    Archive,
    Hollows,
    Forge,
    PaleReach,
    Battle,
    Boss,
    FinalBoss,
    Victory,
    GameOver,
    Story,
    Ending,
    Dawn,
}

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Sfx {
    MenuMove,
    MenuSelect,
    MenuBack,
    Denied,
    TextBlip,
    Step,
    DoorOpen,
    ChestOpen,
    Coin,
    ItemGet,
    Encounter,
    Stairs,
    Waystone,
    Save,
    Hit,
    CritHit,
    Miss,
    Block,
    EnemyDie,
    PartyDown,
    Heal,
    Fire,
    Frost,
    Shock,
    Light,
    Shadow,
    Poison,
    Buff,
    Debuff,
    LevelUp,
    Flee,
    Shard,
    BossRoar,
    Explosion,
}

#[allow(dead_code)]
impl Track {
    pub const ALL: [Track; 16] = [
        Track::Title,
        Track::Town,
        Track::TownSorrow,
        Track::Undercroft,
        Track::Archive,
        Track::Hollows,
        Track::Forge,
        Track::PaleReach,
        Track::Battle,
        Track::Boss,
        Track::FinalBoss,
        Track::Victory,
        Track::GameOver,
        Track::Story,
        Track::Ending,
        Track::Dawn,
    ];

    /// Victory and GameOver play once; everything else loops.
    pub fn loops(self) -> bool {
        !matches!(self, Track::Victory | Track::GameOver)
    }
}

#[allow(dead_code)]
impl Sfx {
    pub const ALL: [Sfx; 34] = [
        Sfx::MenuMove,
        Sfx::MenuSelect,
        Sfx::MenuBack,
        Sfx::Denied,
        Sfx::TextBlip,
        Sfx::Step,
        Sfx::DoorOpen,
        Sfx::ChestOpen,
        Sfx::Coin,
        Sfx::ItemGet,
        Sfx::Encounter,
        Sfx::Stairs,
        Sfx::Waystone,
        Sfx::Save,
        Sfx::Hit,
        Sfx::CritHit,
        Sfx::Miss,
        Sfx::Block,
        Sfx::EnemyDie,
        Sfx::PartyDown,
        Sfx::Heal,
        Sfx::Fire,
        Sfx::Frost,
        Sfx::Shock,
        Sfx::Light,
        Sfx::Shadow,
        Sfx::Poison,
        Sfx::Buff,
        Sfx::Debuff,
        Sfx::LevelUp,
        Sfx::Flee,
        Sfx::Shard,
        Sfx::BossRoar,
        Sfx::Explosion,
    ];
}

/// Fade times (in, out) in seconds when switching to `track`.
fn fades(track: Track) -> (f32, f32) {
    match track {
        // Battles and stings cut in: the field music gets out of the way fast.
        Track::Battle | Track::Boss | Track::FinalBoss => (0.12, 0.6),
        Track::Victory | Track::GameOver => (0.03, 0.4),
        _ => (1.0, 1.0),
    }
}

/// The game's audio. Cheap to call every frame; all synthesis happens on the
/// audio thread.
pub struct Audio {
    #[cfg(feature = "audio")]
    backend: Option<backend::Backend>,
    current: Option<Track>,
    started: Instant,
    /// Seconds after `started` until the current track is over (one-shots).
    until: f32,
}

impl Audio {
    /// Never panics or blocks noticeably (<100 ms). Without an output device, or when
    /// the crate is built without the `audio` feature, every method is a silent no-op.
    pub fn new() -> Self {
        Audio {
            #[cfg(feature = "audio")]
            backend: backend::Backend::start(),
            current: None,
            started: Instant::now(),
            until: f32::INFINITY,
        }
    }

    fn send(&self, cmd: impl FnOnce() -> engine::Cmd) {
        #[cfg(feature = "audio")]
        if let Some(b) = self.backend.as_ref().filter(|b| b.alive()) {
            b.send(cmd());
        }
        #[cfg(not(feature = "audio"))]
        let _ = cmd;
    }

    /// Crossfades (~1 s) to `track`; no-op if it is already the current track.
    /// Victory and GameOver play once and then fall silent; everything else loops seamlessly.
    pub fn play_music(&mut self, track: Track) {
        // Same track: nothing to do, unless it is a one-shot that has finished.
        if self.current == Some(track) && self.started.elapsed().as_secs_f32() < self.until {
            return;
        }
        self.current = Some(track);
        self.started = Instant::now();
        self.until = if track.loops() {
            f32::INFINITY
        } else {
            songs::one_shot_seconds(track)
        };
        let (fade_in, fade_out) = fades(track);
        self.send(|| engine::Cmd::Music {
            song: Some(Box::new(songs::build(track))),
            fade_in,
            fade_out,
        });
    }

    #[allow(dead_code)]
    pub fn stop_music(&mut self) {
        if self.current.take().is_some() {
            self.send(|| engine::Cmd::Music {
                song: None,
                fade_in: 0.0,
                fade_out: 1.0,
            });
        }
    }

    pub fn play_sfx(&mut self, sfx: Sfx) {
        self.send(|| engine::Cmd::Sfx(sfx));
    }

    /// 0.0..=1.0
    pub fn set_music_volume(&mut self, volume: f32) {
        self.send(|| engine::Cmd::MusicVolume(volume));
    }

    pub fn set_sfx_volume(&mut self, volume: f32) {
        self.send(|| engine::Cmd::SfxVolume(volume));
    }

    /// Called once per frame with the frame time in seconds (for fades, if you need it).
    /// Fades run on the audio thread, so this only exists for API symmetry.
    pub fn update(&mut self, dt: f32) {
        let _ = dt;
    }
}

impl Default for Audio {
    fn default() -> Self {
        Self::new()
    }
}

/// Offline rendering through the same engine the game uses (for
/// `examples/render_audio.rs` and the tests). No audio device needed.
#[allow(dead_code)]
pub mod offline {
    use super::{Sfx, Track, engine, songs};

    /// Interleaved stereo samples plus where the loop repeats.
    pub struct Rendered {
        pub samples: Vec<f32>,
        pub rate: u32,
        /// Seconds from the start to the first loop point (end of the first pass).
        pub first_pass: f64,
        /// Seconds where the repeat starts (0 unless the song has an intro).
        pub loop_start: f64,
        pub bpm: f32,
        pub looping: bool,
        /// Loudest sample before the master limiter (above 0.8 it engaged).
        pub peak_before_limiter: f32,
    }

    /// Renders a track: one-shots until they have died away (plus `extra`
    /// seconds of silence); looping tracks for the first pass plus `extra`
    /// seconds into the repeat.
    pub fn render_track(track: Track, rate: u32, extra: f32) -> Rendered {
        let song = songs::build(track);
        let first_pass = song.length_seconds();
        let loop_start = song.loop_start_seconds();
        let bpm = song.bpm;
        let looping = song.looping;
        let mut e = engine::Engine::new(rate);
        e.command(engine::Cmd::Music {
            song: Some(Box::new(song)),
            fade_in: 0.0,
            fade_out: 0.0,
        });
        let mut samples;
        if looping {
            let frames = ((first_pass + extra as f64) * rate as f64) as usize;
            samples = vec![0.0; frames * 2];
            e.render_interleaved(&mut samples);
        } else {
            samples = Vec::new();
            let mut buf = vec![0.0; 1024];
            let max = ((first_pass + 20.0) * rate as f64) as usize * 2;
            while e.music_playing() && samples.len() < max {
                e.render_interleaved(&mut buf);
                samples.extend_from_slice(&buf);
            }
            samples.resize(samples.len() + (extra * rate as f32) as usize * 2, 0.0);
        }
        let peak_before_limiter = e.limiter_stats().0;
        Rendered {
            samples,
            rate,
            first_pass,
            loop_start,
            bpm,
            looping,
            peak_before_limiter,
        }
    }

    /// Renders one sound effect until it has died away (at most 4 s).
    pub fn render_sfx(sfx: Sfx, rate: u32) -> Vec<f32> {
        let mut e = engine::Engine::new(rate);
        e.command(engine::Cmd::Sfx(sfx));
        let mut out = Vec::new();
        let mut buf = vec![0.0; 1024];
        let max = rate as usize * 4;
        let mut quiet = 0;
        while out.len() / 2 < max {
            e.render_interleaved(&mut buf);
            out.extend_from_slice(&buf);
            let peak = buf.iter().fold(0.0f32, |m, x| m.max(x.abs()));
            quiet = if peak < 1e-4 { quiet + 1 } else { 0 };
            if quiet > 4 && out.len() > 8192 {
                break;
            }
        }
        out
    }

    /// Notation errors in the soundtrack (empty when everything parses).
    pub fn song_errors() -> Vec<String> {
        Track::ALL
            .iter()
            .flat_map(|t| songs::build(*t).errors)
            .collect()
    }

    /// Length in seconds of a track's first pass and its tempo.
    pub fn track_info(track: Track) -> (f64, f64, f32) {
        let s = songs::build(track);
        (s.length_seconds(), s.loop_start_seconds(), s.bpm)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// An `Audio` that never touches a device.
    fn silent() -> Audio {
        Audio {
            #[cfg(feature = "audio")]
            backend: None,
            current: None,
            started: Instant::now(),
            until: f32::INFINITY,
        }
    }

    #[test]
    fn songs_parse_cleanly() {
        let errors = offline::song_errors();
        assert!(errors.is_empty(), "{}", errors.join("\n"));
    }

    #[test]
    fn loop_lengths_match_the_brief() {
        for t in Track::ALL {
            let (len, intro, _) = offline::track_info(t);
            if t.loops() {
                let lp = len - intro;
                assert!((45.0..=100.0).contains(&lp), "{t:?}: loop of {lp:.1} s");
            } else {
                assert!(len < 8.0, "{t:?}: {len:.1} s");
            }
        }
    }

    #[test]
    fn one_shots_end_in_silence() {
        for t in [Track::Victory, Track::GameOver] {
            let r = offline::render_track(t, 8000, 0.0);
            let secs = r.samples.len() as f64 / 2.0 / 8000.0;
            assert!(
                secs < r.first_pass + 15.0,
                "{t:?} never finished ({secs:.1} s)"
            );
            let tail = &r.samples[r.samples.len() - 1600..];
            assert!(
                tail.iter().all(|x| x.abs() < 1e-3),
                "{t:?} was cut off while sounding"
            );
            assert!(r.samples.iter().any(|x| x.abs() > 0.05), "{t:?} is silent");
        }
    }

    #[test]
    fn effects_are_short_and_clean() {
        for s in Sfx::ALL {
            let buf = offline::render_sfx(s, 11025);
            assert!(buf.iter().all(|x| x.is_finite() && x.abs() <= 1.0), "{s:?}");
            assert!(buf.iter().any(|x| x.abs() > 0.02), "{s:?} is silent");
            assert!(buf.len() / 2 < 11025 * 4, "{s:?} rings too long");
        }
    }

    #[test]
    fn silent_audio_is_a_no_op() {
        let mut a = silent();
        a.play_music(Track::Town);
        a.play_music(Track::Town);
        a.play_music(Track::Victory);
        a.play_sfx(Sfx::Coin);
        a.set_music_volume(0.5);
        a.set_sfx_volume(2.0);
        a.set_music_volume(f32::NAN);
        a.update(0.016);
        a.stop_music();
        a.stop_music();
    }

    #[test]
    fn new_returns_quickly_and_drops_cleanly() {
        let t = Instant::now();
        let a = Audio::new();
        assert!(t.elapsed().as_millis() < 100);
        drop(a);
    }

    #[test]
    fn audio_can_move_between_threads() {
        fn check<T: Send>() {}
        check::<Audio>();
    }
}
